output: cli
quiet: true
directory: .
framework: terraform
download-external-modules: true
skip-check:
  - CKV_GCP_97 # Mastodon does not support redis tls.
  - CKV_GCP_62 # I cannot get rid of this check also on logging bucket.
