mastodon:
  createAdmin:
    enabled: ${MASTODON_CREATE_ADMIN}
    username: ${MASTODON_ADMIN_USERNAME}
    email: ${MASTODON_ADMIN_EMAIL}
  locale: ${MASTODON_LOCALE}
  local_domain: ${MASTODON_LOCAL_DOMAIN}
  s3:
    enabled: true
    bucket: ${MASTODON_S3_BUCKET_NAME}
    existingSecret: ${MASTODON_S3_EXISTING_SECRET}
    endpoint: https://storage.googleapis.com
    hostname: storage.googleapis.com
  smtp:
    existingSecret: ${MASTODON_SMTP_EXISTING_SECRET}
  secrets:
    secret_key_base: ${MASTODON_SECRET_KEY_BASE}
    otp_secret: ${MASTODON_OTP_SECRET}
    vapid:
      private_key: ${MASTODON_VAPID_PRIVATE_KEY}
      public_key: ${MASTODON_VAPID_PUBLIC_KEY}
  # Always trust GCP GFE ips: https://cloud.google.com/load-balancing/docs/https
  trusted_proxy_ip: ${MASTODON_TRUSTED_PROXY_IP},130.211.0.0/22,35.191.0.0/16
  streaming:
    replicas: 2
  web:
    replicas: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ${MASTODON_GLOBAL_IP_NAME}
    networking.gke.io/managed-certificates: ${NAME}-managed-certificate
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: ${MASTODON_LOCAL_DOMAIN}
      paths:
        - path: "/"
  tls: [] # We don't need this as it's managed by managed-certificates.

# ref: https://github.com/bitnami/charts/tree/main/bitnami/redis#parameters
redis:
  enabled: ${MASTODON_REDIS_ENABLED}
  hostname: ${MASTODON_REDIS_HOSTNAME}
  replica:
    replicaCount: 3
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  # Keep the master on a standard node.
  master:
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
  auth:
    existingSecret: ${MASTODON_REDIS_SECRET_NAME}

# ref: https://github.com/bitnami/charts/tree/main/bitnami/elasticsearch#parameters
## See: https://github.com/bitnami/charts/issues/5641 - https://github.com/bitnami/charts/issues/6694
### Requests are made by sampling an empty installation, tweak them according to your needs.
elasticsearch:
  enabled: true
  sysctlImage:
    enabled: false # THIS IS NOT COMPATIBLE WITH GKE AUTOPILOT.
  extraConfig:
    index.store.type: niofs
    node.store.allow_mmap: false
  master:
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
    heapSize: 512m
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    terminationGracePeriodSeconds: 25
    replicaCount: 1
  data:
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
    heapSize: 512m
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    terminationGracePeriodSeconds: 25
    replicaCount: 1
  coordinating:
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
    heapSize: 512m
    replicaCount: 1
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    terminationGracePeriodSeconds: 25
    replicaCount: 1
  ingest:
    resources:
      requests:
        cpu: 750m
        memory: 1024Mi
    heapSize: 512m
    replicaCount: 1
    nodeSelector:
      cloud.google.com/gke-spot: "true"
    terminationGracePeriodSeconds: 25
    replicaCount: 1

postgresql:
  enabled: false
  postgresqlHostname: ${MASTODON_POSTGRES_HOST}
  postgresqlPort: 5432
  auth:
    database: ${MASTODON_POSTGRES_DB}
    username: ${MASTODON_POSTGRES_USER}
    existingSecret: ${MASTODON_POSTGRES_SECRET_NAME}

service:
  type: NodePort

# Set the minimum resources as default for all pods: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#min-max-requests
# Autopilot requests/limits: https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-resource-requests#min-max-requests
# Pricing calculator done till now: https://cloud.google.com/products/calculator/#id=aabc9042-8fbd-44e1-90d0-e3477a1f0eaf
## EUR 25 per 1 month to run only Mastodon pods, on spot VMs, 5 replicas.
resources:
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector:
  cloud.google.com/gke-spot: "true"
